import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { cn } from "@/lib/utils/cn";
import { TEST_STATUS_COLOR } from "@/constants";
import { formatDate } from "@/lib/utils/formatDate";
export default function RunHistoryCard({ run, onDelete }) {
    const [expanded, setExpanded] = useState(false);
    const [confirmDelete, setConfirmDelete] = useState(false);
    const passRate = run.summary.total > 0
        ? Math.round((run.summary.passed / run.summary.total) * 100)
        : 0;
    return (_jsxs("div", { className: "bg-white border border-gray-200 rounded-xl overflow-hidden", children: [_jsxs("div", { className: "p-4", children: [_jsxs("div", { className: "flex items-start justify-between gap-2", children: [_jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "text-sm font-semibold text-gray-900 truncate", children: run.name }), _jsx("p", { className: "text-xs text-gray-400 mt-0.5", children: formatDate(run.completedAt) })] }), _jsxs("div", { className: "flex items-center gap-2 shrink-0", children: [_jsxs("span", { className: cn("text-xs font-semibold px-2.5 py-0.5 rounded-full", passRate >= 80
                                            ? "bg-green-100 text-green-700"
                                            : passRate >= 50
                                                ? "bg-yellow-100 text-yellow-700"
                                                : "bg-red-100 text-red-700"), children: [passRate, "% pass"] }), _jsx("button", { onClick: () => setExpanded(!expanded), className: "text-xs text-gray-400 hover:text-gray-600 px-1", children: expanded ? "Close ▲" : "Detail ▼" })] })] }), _jsxs("div", { className: "flex flex-wrap gap-1.5 mt-3", children: [run.summary.passed > 0 && (_jsxs("span", { className: "text-[11px] bg-green-50 text-green-700 px-2 py-0.5 rounded-full", children: ["\u2713 ", run.summary.passed, " pass"] })), run.summary.failed > 0 && (_jsxs("span", { className: "text-[11px] bg-red-50 text-red-700 px-2 py-0.5 rounded-full", children: ["\u2717 ", run.summary.failed, " fail"] })), run.summary.blocked > 0 && (_jsxs("span", { className: "text-[11px] bg-orange-50 text-orange-700 px-2 py-0.5 rounded-full", children: ["\u2298 ", run.summary.blocked, " blocked"] })), run.summary.skipped > 0 && (_jsxs("span", { className: "text-[11px] bg-gray-50 text-gray-500 px-2 py-0.5 rounded-full", children: ["\u2014 ", run.summary.skipped, " skip"] })), _jsxs("span", { className: "text-[11px] bg-gray-50 text-gray-400 px-2 py-0.5 rounded-full ml-auto", children: [run.summary.total, " test case"] })] })] }), expanded && (_jsxs("div", { className: "border-t border-gray-100", children: [_jsx("div", { className: "divide-y divide-gray-50", children: Object.entries(run.results).map(([tcId, result]) => (_jsxs("div", { className: "px-4 py-2.5 flex items-start gap-3", children: [_jsx("span", { className: cn("text-[11px] font-medium px-2 py-0.5 rounded-full shrink-0 mt-0.5 capitalize", TEST_STATUS_COLOR[result.status] ??
                                        "bg-gray-100 text-gray-600"), children: result.status }), _jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "text-xs text-gray-700", children: result.title }), result.note && (_jsx("p", { className: "text-[11px] text-gray-400 mt-0.5 italic", children: result.note }))] })] }, tcId))) }), _jsx("div", { className: "px-4 pb-3 pt-2 flex justify-end", children: confirmDelete ? (_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "text-xs text-gray-500", children: "Delete this run?" }), _jsx("button", { onClick: () => setConfirmDelete(false), className: "text-xs text-gray-500 hover:text-gray-700", children: "Cancel" }), _jsx("button", { onClick: onDelete, className: "text-xs text-red-600 hover:text-red-700 font-medium", children: "Delete" })] })) : (_jsx("button", { onClick: () => setConfirmDelete(true), className: "text-xs text-red-400 hover:text-red-600", children: "Delete this run" })) })] }))] }));
}
