import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { cn } from "@/lib/utils/cn";
import { SEVERITY_COLOR, BUG_STATUS_LABEL, BUG_STATUS_COLOR, } from "@/constants";
import { formatDate } from "@/lib/utils/formatDate";
import Modal from "@/components/common/Modal";
export default function BugDetailModal({ bug, reportedByName, onClose, }) {
    const statusDot = BUG_STATUS_COLOR[bug.status];
    return (_jsx(Modal, { title: bug.title, subtitle: "Bug Detail", onClose: onClose, maxWidth: "max-w-lg", children: _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("div", { className: cn("w-2 h-2 rounded-full", statusDot) }), _jsx("span", { className: "text-xs font-medium text-gray-600", children: BUG_STATUS_LABEL[bug.status] })] }), _jsx("span", { className: cn("text-[11px] rounded-full px-2.5 py-0.5 font-semibold capitalize", SEVERITY_COLOR[bug.severity]), children: bug.severity })] }), _jsxs("div", { className: "space-y-1", children: [_jsx("p", { className: "text-xs font-semibold text-gray-500 uppercase tracking-wide", children: "Description" }), _jsx("p", { className: "text-sm text-gray-700 whitespace-pre-wrap", children: bug.description || (_jsx("span", { className: "italic text-gray-400", children: "No description provided." })) })] }), bug.attachments && bug.attachments.length > 0 && (_jsxs("div", { className: "space-y-1", children: [_jsx("p", { className: "text-xs font-semibold text-gray-500 uppercase tracking-wide", children: "Attachments" }), _jsx("ul", { className: "space-y-1", children: bug.attachments.map((url, i) => (_jsx("li", { children: _jsx("a", { href: url, target: "_blank", rel: "noopener noreferrer", className: "text-xs text-indigo-600 hover:underline break-all", children: url }) }, i))) })] })), _jsxs("div", { className: "grid grid-cols-2 gap-3 pt-2 border-t border-gray-100", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs font-semibold text-gray-500 uppercase tracking-wide mb-0.5", children: "Reported By" }), _jsx("p", { className: "text-sm text-gray-700", children: reportedByName })] }), _jsxs("div", { children: [_jsx("p", { className: "text-xs font-semibold text-gray-500 uppercase tracking-wide mb-0.5", children: "Created At" }), _jsx("p", { className: "text-sm text-gray-700", children: formatDate(bug.createdAt) })] })] })] }) }));
}
